#####
# 自動編譯 EXE 並建立 Release（正式版）
#####
name: Auto Build and Release EXE

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write
  issues: write
  actions: write

jobs:
  build_release:
    runs-on: windows-latest
    env:
      PYTHON_VERSION: '3.11'
      EXCLUDE_PATTERNS: '' # 需要排除的檔案（用 ; 分隔）
      # Nuitka 編譯命令
      NUITKA_CMD: 'nuitka app.py --standalone --show-progress --disable-console --remove-output --noinclude-default-mode=nofollow --windows-icon-from-ico=assets/icon.png --include-data-dir=assets=assets --enable-plugin=pyside6 --include-qt-plugins=sensible --lto=yes -j 20 --output-dir=dev/build'

    steps:
      # ----------------------------
      # 1. 拉取倉庫
      # ----------------------------
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ----------------------------
      # 2. 取得版本號
      # ----------------------------
      - name: Get version from Python file
        id: get_version
        shell: bash
        run: |
          VERSION=$(python -c 'import re; print(re.search(r"appVersion\s*=\s*\"([^\"]+)\"", open("src/app_config.py", encoding="utf-8").read()).group(1))')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Detected version: $VERSION"

      # ----------------------------
      # 3. 設定 Python
      # ----------------------------
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # ----------------------------
      # 4. 偵測架構
      # ----------------------------
      - name: Detect architecture
        id: arch
        shell: bash
        run: |
          ARCH=$(python -c "import platform; print('x64' if platform.architecture()[0] == '64bit' else 'x86')")
          echo "arch=$ARCH" >> $GITHUB_OUTPUT
          echo "Detected architecture: $ARCH"

      # ----------------------------
      # 5. 快取 pip
      # ----------------------------
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: $HOME/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml','**/poetry.lock','**/requirements.txt') }}

      # ----------------------------
      # 6. 安裝依賴 (自動偵測 pyproject.toml / pdm / requirements)
      # ----------------------------
      - name: Install dependencies
        shell: bash
        run: |
          set -e
          python -m pip install --upgrade pip
          if grep -q "\[tool.poetry\]" pyproject.toml 2>/dev/null || [ -f poetry.lock ]; then
            echo "Using Poetry..."
            python -m pip install poetry
            poetry config virtualenvs.create false --local
            poetry install --no-interaction --no-ansi --only main
          elif grep -q "\[tool.pdm\]" pyproject.toml 2>/dev/null || [ -f pdm.lock ]; then
            echo "Using PDM..."
            python -m pip install pdm
            pdm install --no-edit --prod
          elif [ -f requirements.txt ]; then
            echo "Using requirements.txt..."
            python -m pip install -r requirements.txt
          else
            echo "Fallback: install current package"
            python -m pip install .
          fi

      # ----------------------------
      # 7. 移除指定檔案
      # ----------------------------
      - name: Remove files
        shell: bash
        run: |
          if [ -n "$EXCLUDE_PATTERNS" ]; then
            IFS=';' read -ra patterns <<< "$EXCLUDE_PATTERNS"
            for p in "${patterns[@]}"; do
              echo "Removing files matching: $p"
              git ls-files -z "$p" | xargs -0 -r rm -f --
              rm -rf "$p" || true
            done
          fi

      # ----------------------------
      # 8. 安裝 Nuitka 與必要依賴
      # ----------------------------
      - name: Install Nuitka
        shell: bash
        run: |
          python -m pip install nuitka numpy pandas scipy matplotlib

      # ----------------------------
      # 9. 下載並解壓 Dependency Walker
      # ----------------------------
      - name: Download and Extract Dependency Walker
        shell: bash
        run: |
          DW_PATH="$LOCALAPPDATA/Nuitka/Nuitka/Cache/downloads/depends/x86_64"
          mkdir -p "$DW_PATH"
          ZIP_FILE="$DW_PATH/depends22_x64.zip"
          curl -L -o "$ZIP_FILE" "https://www.dependencywalker.com/depends22_x64.zip"
          unzip -o "$ZIP_FILE" -d "$DW_PATH"

      # ----------------------------
      # 10. 編譯 EXE
      # ----------------------------
      - name: Build exe with Nuitka
        shell: bash
        run: |
          echo "Running Nuitka build..."
          eval "python -m ${NUITKA_CMD}"

      # ----------------------------
      # 11. 封裝為 ZIP
      # ----------------------------
      - name: Zip output
        id: zip_file
        shell: bash
        run: |
          FILE_NAME="onee_meta_${{ steps.get_version.outputs.version }}_auto-${{ steps.arch.outputs.arch }}"
          echo "file_name=$FILE_NAME" >> $GITHUB_OUTPUT
          powershell Compress-Archive -Path "dev/build/app.dist/*" -DestinationPath "$FILE_NAME.zip" -Force
          echo "Created ZIP: $FILE_NAME.zip"

      # ----------------------------
      # 12. 上傳 artifact
      # ----------------------------
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.zip_file.outputs.file_name }}
          path: ${{ steps.zip_file.outputs.file_name }}.zip

      # ----------------------------
      # 13. 收集 commit 訊息
      # ----------------------------
      - name: Collect commit logs since last release
        id: changelog
        shell: bash
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          echo "Last tag: $LAST_TAG"
          if [ -z "$LAST_TAG" ]; then
            git log --pretty=format:"- %s (%h)" > commits.txt
          else
            git log "$LAST_TAG"..HEAD --pretty=format:"- %s (%h)" > commits.txt
          fi
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          cat commits.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      # ----------------------------
      # 14. 建立 Release（正式版）
      # ----------------------------
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.version }}_Auto
          name: "Version ${{ steps.get_version.outputs.version }} Auto"
          body: |
            ### 變更內容
            ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false
          files: ${{ steps.zip_file.outputs.file_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
